/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package day1puzzle2;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedList;
import java.util.List;
import java.util.stream.Collectors;

public class App {

    public int increases(Path file) {
        var depths = readDepths(file);
        return countDepthIncreases(depths, 3);
    }

    private int countDepthIncreases(List<Integer> depths, int windowSize) {
        var window = new LinkedList<Integer>();
        var prevWindowValue = -1;
        var newWindowValue = -1;
        var increases = 0;
        for (var depth : depths) {
            // feed/maintain the window
            window.addFirst(depth);
            if (window.size() < windowSize) {
                continue;
            }
            if (window.size() > windowSize) {
                window.removeLast();
            }
            // with a full window - calculate value and compare to previous
            newWindowValue = window.stream().reduce(Integer::sum).orElse(0);
            if (prevWindowValue != -1 && newWindowValue > prevWindowValue) {
                increases++;
            }
            prevWindowValue = newWindowValue;
        }
        return increases;
    }

    private List<Integer> readDepths(Path file) {
        try {
            return Files.lines(file)
                    .map(Integer::valueOf)
                    .collect(Collectors.toList());
        } catch (IOException e) {
            e.printStackTrace();
            throw new IllegalStateException("Couldn't read the file", e);
        }
    }

    public static void main(String[] args) {
        var tmpDir = AppUtil.createTempDirectory();
        try {
            var inputFile = AppUtil.writeResourceToFile(tmpDir, "/input.txt");
            System.out.printf("Increases = %s%n", new App().increases(inputFile));
        } finally {
            AppUtil.deleteDirectoryAndChildren(tmpDir);
        }
    }

}
