/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package puzzle;

import java.util.Optional;

public class App {

    /**
     * Reset boards. Play game of Bingo, until a board wins, or
     * until no more numbers to play.
     *
     * @return winning board or null
     */
    public Optional<Board> playToFindFirst(String resourceName) {
        var game = Game.from(resourceName);
        return game.findFirstWinner();
    }

    /**
     * Reset boards. Play game of Bingo, until a board wins, or
     * until no more numbers to play.
     *
     * @return winning board or null
     */
    public Optional<Board> playToFindLast(String resourceName) {
        var game = Game.from(resourceName);
        return game.findLastWinner();
    }

    public static void main(String[] args) {
        findFirstWinner();
        findLastWinner();
    }

    private static void findFirstWinner() {
        var maybeBoard = new App().playToFindFirst("input.txt");
        reportWinner("First", maybeBoard);
    }

    private static void findLastWinner() {
        var maybeBoard = new App().playToFindLast("input.txt");
        reportWinner("Last", maybeBoard);
    }

    private static void reportWinner(String description, Optional<Board> maybeBoard) {
        if (maybeBoard.isPresent()) {
            System.out.printf("%s winning board: %n%s%n", description, maybeBoard.get());
            System.out.printf("- unmarked numbers total: %d%n", maybeBoard.get().totalUnmarkedNumbers());
            System.out.printf("- last number called: %d%n", maybeBoard.get().getLastMarked());
            System.out.printf("- board score: %d%n",
                    maybeBoard.get().totalUnmarkedNumbers() * maybeBoard.get().getLastMarked()
            );
        } else {
            System.out.printf("No winner!%n");
        }
    }

}
