/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package puzzle;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.function.Function;
import java.util.stream.Collectors;

public class App {

    /**
     * Reset boards. Play game of Bingo, until a board wins, or
     * until no more numbers to play.
     * @return winning board or null
     */
    public Optional<Board> playGame(String resourceName) {
        var game = Game.from(resourceName);
        return game.play();
    }

    public static void main(String[] args) {
        var maybeBoard = new App().playGame("input.txt");
        if (maybeBoard.isPresent()) {
            System.out.printf("Winning board: %n%s%n", maybeBoard.get());
            System.out.printf("- unmarked numbers total: %d%n", maybeBoard.get().totalUnmarkedNumbers());
            System.out.printf("- last number called: %d%n", maybeBoard.get().getLastMarked());
            System.out.printf("- board score: %d%n",
                    maybeBoard.get().totalUnmarkedNumbers() * maybeBoard.get().getLastMarked()
            );
        } else {
            System.out.printf("No winner!%n");
        }
    }

}
