/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package day1puzzle2;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import java.nio.file.Path;
import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.assertEquals;

class AppTest {

    private static Path rootDir;

    public static Stream<Arguments> increasesTestData() {
        return Stream.of(
                Arguments.of("/test_input_1number.txt", 0),
                Arguments.of("/test_input_2numbers.txt", 0),
                Arguments.of("/test_input_3numbers.txt", 0),
                Arguments.of("/test_input_4dec_result0.txt", 0),
                Arguments.of("/test_input_4inc_result1.txt", 1),
                Arguments.of("/test_input_5inc_result5.txt", 5),
                Arguments.of("/test_input_no_numbers.txt", 0)
        );
    }

    @ParameterizedTest
    @MethodSource("increasesTestData")
    void increases(String resourceName, int expectedIncreases) {
        var app = new App();
        var file = AppUtil.writeResourceToFile(rootDir, resourceName);
        assertEquals(expectedIncreases, app.increases(file));
    }

    @BeforeAll
    static void setup() {
        rootDir = AppUtil.createTempDirectory();
    }

    @AfterAll
    static void tearDown() {
        AppUtil.deleteDirectoryAndChildren(rootDir);
    }

}
