/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package puzzle;

import java.util.List;
import java.util.stream.Collectors;

public class App {

    private final List<Line> lines;

    public static void main(String[] args) {
        var app = new App("input.txt");
        System.out.printf("Known display digits: %d%n", app.knownDisplayDigits());
    }

    public App(String resourceName) {
        lines = AppUtil.linesFromResource(resourceName)
                .stream()
                .map(Line::new)
                .collect(Collectors.toList());
    }

    public int knownDisplayDigits() {
        return lines
                .stream()
                .map(Line::knownDisplayDigits)
                .reduce(Integer::sum).orElse(0);
    }

}
