/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package puzzle;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import javax.swing.text.Position;
import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.assertEquals;

class AppTest {

    public static Stream<Arguments> findPowerConsumptionData() {
        return Stream.of(
                Arguments.of("/test_input_all_zeroes_0.txt", 0),
                Arguments.of("/test_input_3x3_10.txt", 10)
        );
    }

    @ParameterizedTest
    @MethodSource("findPowerConsumptionData")
    void findPowerConsumption(String resourceName, int expectedPowerConsumption) {
        var app = new App();
        var actualPowerConsumption = app.findPowerConsumption(resourceName);
        assertEquals(expectedPowerConsumption, actualPowerConsumption.value(), actualPowerConsumption.toString());
    }

}
