/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package puzzle;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.assertEquals;

class AppTest {

    public static Stream<Arguments> data() {
        return Stream.of(
                Arguments.of("test_input_single_line_2.txt", 2),
                Arguments.of("test_input_two_lines_5.txt", 5)
        );
    }

    @ParameterizedTest
    @MethodSource("data")
    void knownDisplayDigits(String resourceName, int expectedDigits) {
        assertEquals(expectedDigits, new App(resourceName).knownDisplayDigits());
    }

}
