/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package puzzle;

import java.util.Arrays;
import java.util.stream.Collectors;

public class App {

    public static void main(String[] args) {
        var spawnTimerCsv = AppUtil.resourceAsString("input.txt");
        var spawnTimers = Arrays.stream(spawnTimerCsv.split(","))
                .map(Integer::parseInt)
                .collect(Collectors.toList());
        var simulation = new Simulation(spawnTimers);
        var days = 256;
        simulation.runFor(days);
        System.out.printf("After %d days, there are %d lanternfish%n", days, simulation.fishCount());
    }

}
