/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package puzzle;

import java.util.Arrays;
import java.util.stream.Collectors;

public class App {

    public static void main(String[] args) {
        var spawnTimerCsv = AppUtil.resourceAsString("input.txt");
        var spawnTimers = Arrays.asList(spawnTimerCsv.split(","))
                .stream()
                .map(Integer::parseInt)
                .map(i -> (byte)i.intValue())
                .collect(Collectors.toList());
        var simulation = new Simulation(spawnTimers);
        simulation.runFor(256);
        System.out.printf("After 80 days, there are %d lanternfish%n", simulation.fishCount());
    }

}
