/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package puzzle;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

class AppTest {

    public static Stream<Arguments> data() {
        return Stream.of(
                Arguments.of("test_input_puzzle_sample_mincost_5_168.txt", 5, 168),
                Arguments.of("test_input_three_crabs_mincost_2_2.txt", 2, 2)
        );
    }

    @ParameterizedTest
    @MethodSource("data")
    void findCheapestAlignmentPosition(String resourceName, int expectedPosition, int expectedMinCost) {
        var cheapestPosition = App.findCheapestAlignmentPosition(resourceName);
        assertNotNull(cheapestPosition);
        assertEquals(expectedPosition, cheapestPosition.position());
        assertEquals(expectedMinCost, cheapestPosition.cost());
    }

}
